name: normandy_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter
  camera: ^0.10.0+2
  permission_handler: ^11.3.1
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  path_provider: ^2.0.11
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: 10.7.0
  http: ^1.0.0
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.20
  google_ml_kit: ^0.16.3
  flutter_onedrive: ^1.6.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/.env
    - assets/images/
    - assets/icon.svg
    - assets/images/logo.png
    - assets/images/oneDrive.png
    - assets/images/homeDepot.png
    - assets/images/googleTranslate.png
    - assets/images/hines.png
    - assets/images/menards.png
    - assets/images/outlook.png
    - assets/images/teams.png
    - assets/images/mileage.png
    - assets/images/timeSquared.png
